### PR TITLE
wrong spelling for procedure

### PR DESCRIPTION
**Pull request by vsopvsop**

### CODE REVIEW

**Comment by Dashed** [comment]
@vsopvsop please put all your PRs into one commit!

**Comment by vsopvsop** [comment]
Sir, I am a newbie. What do you mean by PRs?

**Comment by Dashed** [comment]
@vsopvsop PRs = pull requests. 

You're creating a pull request (i.e. branches) for every individual spelling correction: https://github.com/docpad/docpad/pulls/vsopvsop

**Comment by vsopvsop** [comment]
Sir, I myself figured out that. After your prompting, I tried to  add multiple changes in each file. Thanks. Will they give any importance to my humble contribution?

**Comment by balupton** [comment]
No worries, all merged. :dancer:

**Pull request merged**
