### PR TITLE
Use colors in `inspect`

### PR DESCRIPTION
**Pull request by Zearin**
* In `src/lib/util` (typically required as “`docpadUtil`”): Added a simple wrapper around the standard `util.inspect` function (with `{colors:true}` set by default)
* Changed calls to `util.inspect` to `docpadUtil.inspect`

Now, when the user types `docpad info`, their config info is much more readable! ☺

### CODE REVIEW

**Comment by balupton** [comment]
Implementing this now.

**Comment by Zearin** [comment]
> Implementing this now.

w00t w00t!  :+1:

**Comment by Zearin** [comment]
Can someone update this issue’s labels to reflect its “being implemented” status?

**Comment by balupton** [comment]
Will close at the release.

**Comment by balupton** [comment]
Fixed in v6.71.0 February 19, 2015

**Pull request closed without merging**
