### PR TITLE
Formatting problem with code example for DocumentModel class (space i…

### PR DESCRIPTION
**Pull request by SteveMcArthur**
Code example had space indentation rather than tab - killed the formatting when generating the docs

### CODE REVIEW

**Comment by RobLoach** [comment]
This change looks pretty good. Is anything missing from merging?

**Comment by SteveMcArthur** [comment]
Should be no problem merging - its just a matter of checking I haven't made any stupid mistakes or misinterpreted the code.

**Comment by balupton** [comment]
Looks good. I'll review the code changes in more detail when I get to my computer.

**Comment by balupton** [comment]
We should add a note to the HISTORY.md that this fixes the `next` argument for `fixNodePackageVersions` `installNodeModule` and `uninstallNodeModule`

**Comment by SteveMcArthur** [comment]
I'm planning to progressively go through the code and do some tidying up and improvements and then push to this branch. I'm assuming there's no problem merging from the same branch as I go along?

**Comment by balupton** [comment]
Sure. This one did have a change to the code though, which must be documented. As if a release is pushed up, that code change will be pushed up to.

**Comment by SteveMcArthur** [comment]
OK - looking at it now

**Comment by SteveMcArthur** [comment]
Do I just increment the version number to v6.78.5 ?

**Comment by balupton** [comment]
I would have done `## Unreleased`, but that's fine.

**Pull request merged**
