### PR TITLE
fix secondary url redirect

### LINKED ISSUE #850: redirect secondary url to primary url doesn't work
* Your DocPad version `v6.68.1`
* Your Node.js version `v0.10.28`
* Your npm version `1.4.13`
* Your operating system `OS X, x86_64, 10.9`

## What happened
I'm using document secondary urls feature and the redirect doesn't work.

The documented [secondary url](http://docpad.org/docs/meta-data#-url-) feature seems broken:

> `url`
>  When a user accesses a document via a secondary URL, the user will be redirected to the primary URL automatically.

For example, you have a docpad document `/src/documents/secondary-url.html.md`:

    ---
    urls:
     - '/my-secondary-urls1'
     - '/my-secondary-urls2'
    ---
    # primary url should be `secondary-url.html`

## Expectation
it should respond status code 301 with redirect location `/secondary-url.html` when visiting `http://localhost:9778/my-secondary-urls1` while actually docpad responds status code 200.
It seems the feature itself exists based on docpad code: https://github.com/bevry/docpad/blob/572fad61f699e20d0f0516c3e362d4cd7e20270d/src/lib/docpad.coffee#L4619

So I believe this is an issue. Here's [my original question](http://stackoverflow.com/questions/24197428/does-docpad-secondary-url-redirect-feature-work).

### PR DESCRIPTION
**Pull request by shawnzhu**
fix #850

### CODE REVIEW

**Comment by mikeumus** [comment]
@balupton, @Greduan :white_check_mark: :ballot_box_with_check:

**Comment by balupton** [comment]
Seems good. I wonder why it was that way before - seems strange. Happy to do a release and see what happens - the added tests instil confidence.

**Comment by shawnzhu** [comment]
@balupton the code change is just a correct by what the comment `# Check if we are the desired url` said. anything I can do with this PR?

**Comment by balupton** [comment]
Will merge this soon.

**Comment by balupton** [comment]
Fixed in v6.71.0 February 19, 2015

**Pull request merged**
